name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: PHP ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.0
            allow_fail: false
            name: 'PHP 8.0 with latest deps'
          - php: 8.0
            allow_fail: false
            name: 'PHP 8.0 with lowest stable deps'
            composer_update_flags: '--prefer-lowest --prefer-stable'
          - php: 8.1
            allow_fail: false
            name: 'PHP 8.1 with latest deps'
          - php: 8.1
            allow_fail: false
            name: 'PHP 8.1 with lowest stable deps'
            composer_update_flags: '--prefer-lowest --prefer-stable'
          - php: 8.2
            allow_fail: false
            name: 'PHP 8.2 with latest deps'
          - php: 8.2
            allow_fail: false
            name: 'PHP 8.2 with lowest stable deps'
            composer_update_flags: '--prefer-lowest --prefer-stable'
          - php: 8.3
            allow_fail: false
            name: 'PHP 8.3 with latest deps'
          - php: 8.3
            allow_fail: false
            name: 'PHP 8.3 with lowest stable deps'
            composer_update_flags: '--prefer-lowest --prefer-stable'
          - php: 8.4
            allow_fail: false
            name: 'PHP 8.4 with latest deps'
          - php: 8.4
            allow_fail: false
            name: 'PHP 8.4 with lowest stable deps'
            composer_update_flags: '--prefer-lowest --prefer-stable'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring, intl, xml, fileinfo, zip
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Update dependencies
        if: matrix.composer_update_flags
        run: composer update ${{ matrix.composer_update_flags }}

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
        continue-on-error: ${{ matrix.allow_fail }}

      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
        continue-on-error: ${{ matrix.allow_fail }}

      - name: Check for vulnerabilities
        if: ${{ contains(matrix.composer_update_flags, '--prefer-lowest') == false }}
        run: composer security-checker
        continue-on-error: ${{ matrix.allow_fail }}

  composer-normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Composer normalize
        uses: localheinz/composer-normalize-action@0.5.2
